// <auto-generated />
using System;
using Assignmet_EF_D2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignmet_EF_D2.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20241129185921_v6")]
    partial class v6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignmet_EF_D2.Models.Author", b =>
                {
                    b.Property<int>("Author_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Author_Id"));

                    b.Property<string>("Bref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Author_Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Author_Id = 1,
                            Bref = "",
                            JoinDate = new DateOnly(2009, 7, 2),
                            Name = "Habiba Mohamed",
                            Password = "12345",
                            Username = "Habiba"
                        },
                        new
                        {
                            Author_Id = 2,
                            Bref = "",
                            JoinDate = new DateOnly(2005, 8, 31),
                            Name = "Tasnim Mohamed",
                            Password = "12345",
                            Username = "tasnim"
                        });
                });

            modelBuilder.Entity("Assignmet_EF_D2.Models.Catalog", b =>
                {
                    b.Property<int>("Catalog_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Catalog_Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Catalog_Id");

                    b.ToTable("Catalog");

                    b.HasData(
                        new
                        {
                            Catalog_Id = 1,
                            Description = "Sports",
                            Name = "Sports"
                        },
                        new
                        {
                            Catalog_Id = 2,
                            Description = "Beuaty",
                            Name = "Beuaty"
                        });
                });

            modelBuilder.Entity("Assignmet_EF_D2.Models.News", b =>
                {
                    b.Property<int>("News_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("News_Id"));

                    b.Property<int>("Auther_Id")
                        .HasColumnType("int");

                    b.Property<string>("Bref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Catalog_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("News_Id");

                    b.HasIndex("Auther_Id");

                    b.HasIndex("Catalog_Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            News_Id = 1,
                            Auther_Id = 1,
                            Bref = "Football",
                            Catalog_Id = 1,
                            DateTime = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "collective game"
                        },
                        new
                        {
                            News_Id = 2,
                            Auther_Id = 1,
                            Bref = "Padel",
                            Catalog_Id = 1,
                            DateTime = new DateTime(2002, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "individual game"
                        });
                });

            modelBuilder.Entity("Assignmet_EF_D2.Models.News", b =>
                {
                    b.HasOne("Assignmet_EF_D2.Models.Author", "author")
                        .WithMany("news")
                        .HasForeignKey("Auther_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignmet_EF_D2.Models.Catalog", "catalog")
                        .WithMany("News")
                        .HasForeignKey("Catalog_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");

                    b.Navigation("catalog");
                });

            modelBuilder.Entity("Assignmet_EF_D2.Models.Author", b =>
                {
                    b.Navigation("news");
                });

            modelBuilder.Entity("Assignmet_EF_D2.Models.Catalog", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
